InterviewTask/Controllers/CartController.cs
using InterviewTask.Models;
using InterviewTask.Repositories;
using InterviewTask.Repositories.Interfaces;
using InterviewTask.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InterviewTask.Controllers
{
    public class CartController : Controller
    {
        private readonly IShoppingCartRepository shoppingCartRepository;
        private readonly IGenericRepository<Item> genericRepository;
        public CartController()
        {
            shoppingCartRepository = new ShoppingCartRepository();
            genericRepository = new GenericRepository<Item>();
        }
        // GET: Cart
        public ActionResult Index()
        {
           string cartId = Session["CartId"].ToString();
            ShoppingCartViewModel shoppingCartViewModel = new ShoppingCartViewModel
            {
                ShoppingCartItems=shoppingCartRepository.GetShoppingCartItems(cartId),
                ShoppingCartTotal=shoppingCartRepository.GetShoppingCartTotal(cartId)
            };
            return View(shoppingCartViewModel);
        }
        public ActionResult AddToCart(int itemId)
        {
            string cartId = Session["CartId"].ToString();
            var selectedItem = genericRepository.Get(itemId);
            shoppingCartRepository.AddToCart(selectedItem, cartId);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult RemoveFromCart(int id)
        {
            shoppingCartRepository.RemoveFromCart(id);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult ClearCart()
        {
            string cartId = Session["CartId"].ToString();
            shoppingCartRepository.ClearCart(cartId);
            return RedirectToAction(nameof(Index));
        }
    }
}

InterviewTask/Controllers/OrderController.cs
using InterviewTask.Models;
using InterviewTask.Repositories;
using InterviewTask.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InterviewTask.Controllers
{
    public class OrderController : Controller
    {
        private readonly OrderRepository orderRepository;
        private readonly ShoppingCartRepository shoppingCartRepository;
        private readonly ApplicationDbContext context;

        public OrderController()
        {
            orderRepository = new OrderRepository();
            shoppingCartRepository = new ShoppingCartRepository();
            context = new ApplicationDbContext();

        }

        // GET: Order
        [Authorize(Roles ="Customer")]
        public ActionResult Index()
        {
            int customerCode = context.Users.Where(u => u.UserName == User.Identity.Name).SingleOrDefault().CustomerCode;
            OrderHeader orderHeader = orderRepository.GetOrderHeader(customerCode);
            List<OrderDetail> orderDetails = orderRepository.GetOrderDetails(orderHeader.Id);
            OrderViewModel orderViewModel = new OrderViewModel
            { 
               OrderHeader=orderHeader,
               OrderDetail=orderDetails
            };
            return View(orderViewModel);
        }

        [Authorize(Roles = "Customer")]
        public ActionResult CheckOut()
        {
            int customerCode = context.Users.Where(u => u.UserName == User.Identity.Name).SingleOrDefault().CustomerCode;
            string cartId = Session["CartId"].ToString();
            var cartItems = shoppingCartRepository.GetShoppingCartItems(cartId);
            if (cartItems.Count==0)
            {
                ModelState.AddModelError("", "Your cart is empty");
            }
            if (ModelState.IsValid)
            {
                orderRepository.CreateOrder(cartItems, customerCode);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

InterviewTask/Controllers/ShopController.cs
using InterviewTask.Models;
using InterviewTask.Repositories;
using InterviewTask.Repositories.Interfaces;
using System.Web.Mvc;

namespace InterviewTask.Controllers
{
    public class ShopController : Controller
    {
        private readonly IGenericRepository<Item> genericRepository;
        public ShopController()
        {
            genericRepository = new GenericRepository<Item>();
        }
        // GET: Shop
        public ActionResult Index()
        {
            return View(genericRepository.GetAll());
        }
    }
}

InterviewTask/Controllers/UOMController.cs
using InterviewTask.Models;
using InterviewTask.Repositories;
using InterviewTask.Repositories.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InterviewTask.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UOMController : Controller
    {
        private readonly IGenericRepository<UOM> genericRepository;
        public UOMController()
        {
            genericRepository = new GenericRepository<UOM>();
        }
        // GET: UOM
        public ActionResult Index()
        {
            return View(genericRepository.GetAll());
        }


        // GET: UOM/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UOM/Create
        [HttpPost]
        public ActionResult Create(UOM uom)
        {
            if (ModelState.IsValid)
            {
                genericRepository.Add(uom);
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: UOM/Edit/5
        public ActionResult Edit(int id)
        {
            return View(genericRepository.Get(id));
        }

        // POST: UOM/Edit/5
        [HttpPost]
        public ActionResult Edit(UOM uom)
        {
            if (ModelState.IsValid)
            {
                genericRepository.Edit(uom);
                return RedirectToAction("Index");
            }
            return View();
        }

        // POST: UOM/Delete/5
        public ActionResult Delete(int id)
        {
            if (ModelState.IsValid)
            {
                genericRepository.Delete(id);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

InterviewTask/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Super Market Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Super Market", "Index", "Shop", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Shop", "Index", "Shop")</li>
                    <li>@Html.ActionLink("View My Cart", "Index", "Cart")</li>
                    <li>@Html.ActionLink("View My Order", "Index", "Order")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Products", "Index", "Products")</li>
                        <li>@Html.ActionLink("Units of Measure", "Index", "UOM")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>